*& ----------------------Auto Peças Padre Cicero-----------------------*
*& Programa : ZMMR035                                                  *
*& Descrição: Relatório para cotação de compras                        *
*& Autor    : Erisom Almeida                                           *
*& Data     : 31/10/2023                                               *
*& Request  : DEVK930587                                               *
*& ID Asana : MM.445780                                                *
*&---------------------------------------------------------------------*
*& Histórico das modificações                                          *
*& Data       Nome             Request    Descrição                    *
*&---------------------------------------------------------------------*

REPORT zmmr035.

INCLUDE ZMMR035_TOP.

INCLUDE ZMMR035_S01.

INCLUDE ZMMR035_C01.
